### ISSUE TITLE
Message for Jerry regarding webservices

### ISSUE THREAD

**Issue by steepleian** [steepleian/weewx-Weather34-development-archive#2]
I had not spotted that you were using a different folder name, sorry for that. Most of the services now running but some having an issue: -

It looks like that additional quotes and spaces are being inserted for some reason.

22:45:19 testpi weewx[2016] ERROR user.weather34: Failed getting web service data. URL: ['https://api.forecast.io/forecast/aef5619cc72559ae65fcd0e6efa76091/51.94', '-0.987?lang=en&units=uk2'] Header: ["'User-Agent'", "'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3'"], Error: <urlopen error unknown url type: ['https>
Sep  2 22:45:19 testpi weewx[2016] ERROR user.weather34: Failed getting web service data. URL: ['https://api.weather.com/v3/wx/forecast/daily/5day?geocode=51.94', '-0.987&language=en&format=json&units=h&apiKey=f29501f88fb143149501f88fb17314f3'] Header: ["'User-Agent'", "'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3'"], Error: <urlopen error unknown url type: ['https>
Sep  2 22:45:19 testpi weewx[2016] ERROR user.weather34: Failed getting web service data. URL: ['https://api.aerisapi.com/alerts/51.940', '-0.987?client_id=JL7SxOao1MSw3GiH5vN0e&client_secret=aUtNCEzT5I8seHzBYk84ROKTQdbEo2xGYE2Lo4on'] Header: ["'User-Agent'", "'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3'"], Error: <urlopen error unknown url type: ['https>
Sep  2 22:45:19 testpi weewx[2016] ERROR user.weather34: Failed getting web service data. URL: ['https://api.aerisapi.com/forecasts/51.940', '-0.987?&format=json&filter=daynight&limit=10&client_id=JL7SxOao1MSw3GiH5vN0e&client_secret=aUtNCEzT5I8seHzBYk84ROKTQdbEo2xGYE2Lo4on'] Header: ["'User-Agent'", "'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3'"], Error: <urlopen error unknown url type: ['https>
Sep  2 22:45:19 testpi weewx[2016] ERROR user.weather34: Failed getting web service data. URL: ['https://api.aerisapi.com/forecasts/51.940', '-0.987?&format=json&filter=1hr&limit=10&fields=periods.dateTimeISO', 'loc', 'periods.maxTempC', 'periods.minTempC', 'periods.pop', 'periods.precipMM', 'periods.maxHumidity', 'periods.windDirMax', 'periods.windSpeedMaxKPH', 'periods.weather&client_id=JL7SxOao1MSw3GiH5vN0e&client_secret=aUtNCEzT5I8seHzBYk84ROKTQdbEo2xGYE2Lo4on'] Header: ["'User-Agent'", "'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3'"], Error: <urlopen error unknown url type: ['https>
Sep  2 

They are correctly formated in weewx.conf

[Weather34WebServices]
    aq_url = https://api.waqi.info/feed/geo:51.940;-0.987/?token=c109e60557fe3d3bceb6bafbca30f2a79e3efd5a
    aq_interval = 300
    aq_filename = /var/www/html/weewx/weather34/jsondata/aqi.txt
    ds_url = https://api.forecast.io/forecast/aef5619cc72559ae65fcd0e6efa76091/51.94,-0.987?lang=en&units=uk2
    ds_interval = 3600
    ds_filename = /var/www/html/weewx/weather34/jsondata/darksky.txt
    wu_url = https://api.weather.com/v3/wx/forecast/daily/5day?geocode=51.94,-0.987&language=en&format=json&units=h&apiKey=f29501f88fb143149501f88fb17314f3
    wu_interval = 3600
    wu_filename = /var/www/html/weewx/weather34/jsondata/wuforecast.txt
    eq_url = https://earthquake-report.com/feeds/recent-eq?json
    eq_interval = 3600
    eq_filename = /var/www/html/weewx/weather34/jsondata/eqnotification.txt
    ki_url = https://services.swpc.noaa.gov/products/geospace/planetary-k-index-dst.json
    ki_interval = 43200
    ki_filename = /var/www/html/weewx/weather34/jsondata/kindex.txt
    me_url = https://api.checkwx.com/metar/EGTK/decoded
    me_header = X-API-Key:f3b57efab1b5a3202acb31a937
    me_interval = 3600
    me_filename = /var/www/html/weewx/weather34/jsondata/metar34.txt
    pu_url = https://www.purpleair.com/json?show=38365
    pu_interval = 300
    pu_filename = /var/www/html/weewx/weather34/jsondata/purpleair.txt
    al_url = http://192.168.1.232/weewx/weather34/eualert.php?country=UK&region=013
    al_interval = 3600
    al_filename = /var/www/html/weewx/weather34/jsondata/meteoalarm.txt
    aa_url = https://api.aerisapi.com/alerts/51.940,-0.987?client_id=JL7SxOao1MSw3GiH5vN0e&client_secret=aUtNCEzT5I8seHzBYk84ROKTQdbEo2xGYE2Lo4on
    aa_interval = 3600
    aa_filename = /var/www/html/weewx/weather34/jsondata/aerisalerts.txt
    ah_url = https://api.aerisapi.com/forecasts/51.940,-0.987?&format=json&filter=1hr&limit=10&fields=periods.dateTimeISO,loc,periods.maxTempC,periods.minTempC,periods.pop,periods.precipMM,periods.maxHumidity,periods.windDirMax,periods.windSpeedMaxKPH,periods.weather&client_id=JL7SxOao1MSw3GiH5vN0e&client_secret=aUtNCEzT5I8seHzBYk84ROKTQdbEo2xGYE2Lo4on
    ah_interval = 3600
    ah_filename = /var/www/html/weewx/weather34/jsondata/aerishour.txt
    ao_url = https://api.aerisapi.com/forecasts/51.940,-0.987?&format=json&filter=daynight&limit=10&client_id=JL7SxOao1MSw3GiH5vN0e&client_secret=aUtNCEzT5I8seHzBYk84ROKTQdbEo2xGYE2Lo4on
    ao_interval = 3600
    ao_filename = /var/www/html/weewx/weather34/jsondata/aerisoutlook.txt
    services = ds.me.eq.ki.wu.aq.al.ah.ao.aa.pu

**Comment by balloonhotair** [comment]
Strange I have no issues.

**Comment by steepleian** [comment]
If I cut and paste those 4 urls as they are in weewx.conf into a browser,
they all give a valid return.

**Comment by balloonhotair** [comment]
What 4 urls are not working and to see from what is posted

**Comment by balloonhotair** [comment]
Location of the weewx.conf file on the system
